### ISSUE TITLE
Some vertical slabs are glitched out when using shaders

### ISSUE THREAD

**Issue by flashifloosh** [lublak/leafing#6]
### Some vertical slabs are glitched out with shaders (also the internal optifine shader):

- **oak** slab
- **spruce** slab
- **birch** slab
- **jungle** slab
- **acacia** slab
- **dark oak** slab
- **crimson** slab
- **warped** slab

![image](https://user-images.githubusercontent.com/63459112/112185847-e41e1f00-8c00-11eb-8e74-77ad01a0a8f1.png)
![image](https://user-images.githubusercontent.com/63459112/112185922-f4ce9500-8c00-11eb-8516-01652f969f5c.png)

_They are working without any shader but it is still throwing an OpenGL error (1281)._

**Comment by lublak** [comment]
how about the quark vertical slabs from oak, spruce, etc?

**Comment by flashifloosh** [comment]
Looking fine as they should.
![image](https://user-images.githubusercontent.com/63459112/112222304-ce245480-8c28-11eb-8540-67b5ceb31e7e.png)

**Comment by lublak** [comment]
@FlashiFlasche 
https://github.com/CJMinecraft01/DoubleSlabs/issues/99
https://github.com/CJMinecraft01/DoubleSlabs/issues/101
https://github.com/CJMinecraft01/DoubleSlabs/issues/166

DoubleSlabs have multiple issues open.
I will test today again, in how far the lags spikes, which are currently present, reduce, if this mod would not be included.
As an alternative, chisel & bits could be used, which is included in the modpack.

**Comment by lublak** [comment]
has been removed
